name: Deploy to Beta channel on push
on:
  push:
    branches:
      - beta
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
        env:
          REACT_APP_BETA_CHANNEL: "true"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOBER_SAILOR_BETA }}'
          channelId: live
          projectId: sober-sailor-beta
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
  deploy_except_hosting:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - run: npm run install-all
      - run: npx firebase-tools --only functions,firestore --token "$FIREBASE_TOKEN" --project sober-sailor-beta
        env:
          BETA_CHANNEL: "true"
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOBER_SAILOR_BETA }}'
